name: 'Run IronPython'
description: 'A GitHub Action that runs a Python script with a Hello, World! program.'
author: 'Your Name'
inputs: {}
runs:
  using: 'composite'
  steps:
    - run: ipy hello-github.py
branding:
  icon: "package"
  color: "purple"